apiVersion: apps/v1
kind: Deployment
metadata:
  name: bildur
  namespace: bildur
  labels:
    app: bildur
spec:
  revisionHistoryLimit: 0
  replicas: 1
  selector:
    matchLabels:
      app: bildur
  template:
    metadata:
      labels:
        app: bildur
    spec:
      containers:
      - name: bildur    
        image: bildur:1.0.0
        imagePullPolicy: IfNotPresent
        ports:
          - name: http
            containerPort: 8080
        resources:
          requests:
            memory: "500Mi"
            cpu: "200m"
          limits:
            memory: "1500Mi"
          
        env:
          - name: "Authority"
            value: {{.Values.helseId.authority}}
